In [1]:
#list comprehention
# Numpy 벡터화 연산과 비교하기 위한 list 예제
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]
print(new_list) 

[2, 4, 6]


In [3]:
# 벡터화 연산 예시 - list 보다 어떤 차이점, 편리성이 더 있는지 생각하기
import numpy as np
my_array = np.array([1, 2, 3])
new_array = my_array * 2    # 벡터화된 연산
print(new_array)

[2 4 6]


In [49]:
arr = np.arange(0, 6, 2)   # arange(start, stop, step) [주의!! stop-1]
print(arr)

[0 2 4]


In [50]:
# rand randn() randint(a, b, size) choice() 
rr = np.random.randn(3, 3)
print(arr)

[[ 0.66973894  0.25609953  0.99057958]
 [ 1.52608631  0.60344296  0.1120467 ]
 [-0.01421282  1.81665961 -1.20317725]]


In [9]:
arr = arr.reshape(1, 9)
print(arr)

[[0.55952854 0.54823224 0.54917339 0.5702846  0.51632867 0.40131912
  0.80669088 0.41946238 0.66032695]]


In [10]:
npsum = np.sum([1,2,3])
print(npsum)

6


In [17]:
# mean : 평균값
arr = np.mean([1,2,3])
print(arr)

2.0


In [18]:
# 교재 표준편차 예제 참조
# std : 표준편차   
arr = np.std([175,177,179,181,183]) 
print(arr)  

2.8284271247461903


In [19]:
#1부터 10까지의 숫자를 가진 배열 생성
import numpy as np
data = np.arange(1, 11)
print(data)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
# 합 계산
sum_data = np.sum(data)
print("합", sum_data)

합 55


In [22]:
# 평균 계산
mean_data = np.mean(data)
print("평균", mean_data)

평균 5.5


In [24]:
# 표준편차 계산
std_data = np.std(data)
print("표준편차", std_data)

표준편차 2.8722813232690143


In [26]:
# 2차원 배열 생성
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
# 전체 요소의 합
sum_all = np.sum(data)
print("전체 요소의 합:", sum_all)

전체 요소의 합: 45


In [27]:
# 각 행의 합
row_sum = np.sum(data, axis=1)
print("각 행의 합:", row_sum)

각 행의 합: [ 6 15 24]


In [28]:
# 각 열의 합
col_sum = np.sum(data, axis=0)
print("각 열의 합:", col_sum)

각 열의 합: [12 15 18]


In [29]:
# 전체 요소의 평균
mean_all = np.mean(data, axis=1)
print("각 행의 평균:", mean_all)

각 행의 평균: [2. 5. 8.]


In [30]:
# 각 행의 평균
row_mean = np.mean(data, axis=1)
print("각 행의 평균:", row_mean)

각 행의 평균: [2. 5. 8.]


In [31]:
# 각 열의 평균
col_mean = np.mean(data, axis=0)
print("각 열의 평균: ", col_mean)

각 열의 평균:  [4. 5. 6.]


In [32]:
# 전체 요소의 표준편차
std_all = np.std(data)
print("전체 요소의 표준편차: " ,std_all)

전체 요소의 표준편차:  2.581988897471611


In [33]:
# 각 행의 표준편차
row_std = np.std(data, axis=1)
print("각 행의 표준편차:", row_std)

각 행의 표준편차: [0.81649658 0.81649658 0.81649658]


In [36]:
# 각 열의 표준편차
col_std = np.std(data, axis=0)
print("각 열의 표준편차:", col_std)

각 열의 표준편차: [2.44948974 2.44948974 2.44948974]


In [40]:
# 1차원 배열 생성
arr1 = np.array([1,2,3,4,5])
# 2차원 배열 생성
arr2 = np.array([[1,2,3],
                [4,5,6]])

# 배열의 shape확인
print(arr2.shape)

(2, 3)


In [41]:
# 특정 요소에 접근 
print(arr2[1,2])    # 두 번째 행, 세 번째 열

6


In [42]:
# 슬라이싱
print(arr2[:, 1])   # 모든 행의 두 번째 열

[2 5]


In [1]:
# 특정 요소에 접근
print(arr2[0][1])    # 첫 번째 행의 두 번쨰 요소(특정 위치의 값을 가져올 때)

NameError: name 'arr2' is not defined