In [ ]:
#list comprehention
# Numpy 벡터화 연산과 비교하기 위한 list 예제
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]
print(new_list) 

[2, 4, 6]


In [ ]:
# 벡터화 연산 예시 - list 보다 어떤 차이점, 편리성이 더 있는지 생각하기
import numpy as np
my_array = np.array([1, 2, 3])
new_array = my_array * 2    # 벡터화된 연산
print(new_array)

[2 4 6]


In [5]:
arr = np.arange(0, 10, 2)   # arange(start, stop, step)
print(arr)

[0 2 4 6 8]


In [8]:
arr = np.random.rand(3, 3)
print(arr)

[[0.55952854 0.54823224 0.54917339]
 [0.5702846  0.51632867 0.40131912]
 [0.80669088 0.41946238 0.66032695]]


In [9]:
arr = arr.reshape(1, 9)
print(arr)

[[0.55952854 0.54823224 0.54917339 0.5702846  0.51632867 0.40131912
  0.80669088 0.41946238 0.66032695]]


In [10]:
npsum = np.sum([1,2,3])
print(npsum)

6


In [ ]:
# mean : 평균값
np.mean([1,2,3])

np.float64(2.0)